from __future__ import annotations

import argparse
import random
import uuid
from datetime import datetime, timezone

from sqlalchemy import delete

from ugc_service.config import get_settings
from ugc_service.db import init_engine, run_migrations, session_scope
from ugc_service.models import MovieRating, MovieReview, ReviewVote, UserBookmark


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate synthetic UGC dataset in PostgreSQL.")
    parser.add_argument("--users", type=int, default=10_000, help="Total unique users.")
    parser.add_argument("--movies", type=int, default=3_000, help="Total unique movies.")
    parser.add_argument("--ratings", type=int, default=200_000, help="Total movie ratings.")
    parser.add_argument("--reviews", type=int, default=60_000, help="Total movie reviews.")
    parser.add_argument("--review-votes", type=int, default=300_000, help="Total review votes.")
    parser.add_argument(
        "--bookmarks-per-user",
        type=int,
        default=10,
        help="Bookmarks per each generated user.",
    )
    parser.add_argument("--seed", type=int, default=42, help="Deterministic random seed.")
    parser.add_argument(
        "--truncate",
        action="store_true",
        help="Cleanup UGC tables before loading synthetic data.",
    )
    return parser.parse_args()


def _build_user_id(index: int) -> str:
    return f"user-{index}"


def _build_movie_id(index: int) -> str:
    return f"movie-{index}"


def _random_score() -> int:
    pivot = random.random()
    if pivot < 0.35:
        return 10
    if pivot < 0.40:
        return 0
    return random.randint(1, 9)


def truncate_tables() -> None:
    with session_scope() as session:
        session.execute(delete(ReviewVote))
        session.execute(delete(MovieReview))
        session.execute(delete(MovieRating))
        session.execute(delete(UserBookmark))


def generate(args: argparse.Namespace) -> None:
    random.seed(args.seed)
    settings = get_settings()
    init_engine(settings.ugc_database_url)
    run_migrations(settings.ugc_database_url)
    if args.truncate:
        truncate_tables()

    users = [_build_user_id(i) for i in range(args.users)]
    movies = [_build_movie_id(i) for i in range(args.movies)]
    now = datetime.now(timezone.utc)

    ratings_rows: list[dict] = []
    ratings_seen: set[tuple[str, str]] = set()
    while len(ratings_rows) < args.ratings:
        user_id = random.choice(users)
        movie_id = random.choice(movies)
        key = (user_id, movie_id)
        if key in ratings_seen:
            continue
        ratings_seen.add(key)
        ratings_rows.append({"user_id": user_id, "movie_id": movie_id, "score": _random_score()})

    reviews_rows: list[dict] = []
    for _ in range(args.reviews):
        reviews_rows.append(
            {
                "id": str(uuid.uuid4()),
                "movie_id": random.choice(movies),
                "user_id": random.choice(users),
                "review_text": f"Autogenerated review {uuid.uuid4().hex[:8]}",
                "movie_score": _random_score(),
                "created_at": now,
                "updated_at": now,
            }
        )

    review_ids = [row["id"] for row in reviews_rows]
    votes_rows: list[dict] = []
    votes_seen: set[tuple[str, str]] = set()
    while len(votes_rows) < args.review_votes:
        user_id = random.choice(users)
        review_id = random.choice(review_ids)
        key = (user_id, review_id)
        if key in votes_seen:
            continue
        votes_seen.add(key)
        votes_rows.append(
            {"user_id": user_id, "review_id": review_id, "vote": random.choice([-1, 1])}
        )

    bookmarks_rows: list[dict] = []
    for user_id in users:
        bookmarked = set()
        for _ in range(args.bookmarks_per_user):
            movie_id = random.choice(movies)
            if movie_id in bookmarked:
                continue
            bookmarked.add(movie_id)
            bookmarks_rows.append({"user_id": user_id, "movie_id": movie_id})

    with session_scope() as session:
        session.bulk_insert_mappings(MovieRating.__mapper__, ratings_rows)
        session.bulk_insert_mappings(MovieReview.__mapper__, reviews_rows)
        session.bulk_insert_mappings(ReviewVote.__mapper__, votes_rows)
        session.bulk_insert_mappings(UserBookmark.__mapper__, bookmarks_rows)

    print("Synthetic data generated:")
    print(f"- users: {len(users)}")
    print(f"- movies: {len(movies)}")
    print(f"- ratings: {len(ratings_rows)}")
    print(f"- reviews: {len(reviews_rows)}")
    print(f"- review_votes: {len(votes_rows)}")
    print(f"- bookmarks: {len(bookmarks_rows)}")


if __name__ == "__main__":
    generate(parse_args())
